---
### ---------------------------------------------------------------------------
### DIFF THE CONFIGURATION TO SEE IF CHANGES ARE NEEDED
### ---------------------------------------------------------------------------
- name: "### Retrieving the configuration as human readable text"
  juniper_junos_config:
    user: "{{ provider_info.user }}"
    passwd: "{{ provider_info.passwd }}"
    # ssh_private_key_file: "{{ provider_info.ssh_private_key_file }}"
    retrieve: "committed"
    format: text
    diff: false
    check: false
    commit: false
  register: committed


### ------------------------------------------------------------
### SAVING CONFIGURATIONS AS A VARIABLE TO BE USED LATER ON
### ------------------------------------------------------------
- name: "### REACH IN AND GRAB THE .config KEY/VALUE FROM HUMAN CONFIG"
  set_fact:
    committed_config: "{{ committed.config }}"


### ------------------------------------------------------------
### debug
### ------------------------------------------------------------

- name: "### PRINT THE RESULT TO CONSOLE ###"
  debug:
    var: committed_config
