configuration:
  interfaces:
    interface:
      # ### PHYSICAL INTERFACES
      - name: xe-0/1/0
        description: "[xe-0/1/0] Connected to dist1 xe-0/0/0"
        ether_options:
          ieee_802.3ad:
            bundle: ae11

      - name: xe-0/1/1
        description: "[xe-0/1/1] Connected to dist1 xe-0/0/1"
        ether_options:
          ieee_802.3ad:
            bundle: ae11

      - name: xe-0/1/2
        description: "[xe-0/1/2] Connected to dist2 xe-0/0/4"
        ether_options:
          ieee_802.3ad:
            bundle: ae12

      - name: xe-0/1/3
        description: "[xe-0/1/3] Connected to dist2 xe-0/0/5"
        ether_options:
          ieee_802.3ad:
            bundle: ae12

      - name: xe-0/1/4
        description: "[xe-0/1/4] Connected to rwan xe-0/0/2:0"
        ether_options:
          ieee_802.3ad:
            bundle: ae13

      - name: xe-0/1/5
        description: "[xe-0/1/5] Connected to rwan xe-0/0/2:1"
        ether_options:
          ieee_802.3ad:
            bundle: ae13
    
      - name: xe-0/1/6
        description: "[xe-0/1/6] Connected to srx"
        ether_options:
          ieee_802.3ad:
            bundle: ae16

      - name: xe-0/1/7
        description: "[xe-0/1/7] Connected to srx"
        ether_options:
          ieee_802.3ad:
            bundle: ae16

      # ### AE INTERFACES
      - name: ae11
        description: "Connected to dist-sw1 (members: xe-0/0/0-1)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "172.16.0.0/31"

      - name: ae12
        description: "Connected to dist-sw2 (members: xe-0/0/4-5)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "172.16.1.0/31"

      - name: ae13
        description: "Connected to rwan (members: xe-0/0/2:0-1)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "172.16.10.0/31"
        
      - name: ae16
        description: "Connected to srx (members: xe-0/1/6-7)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          - name: "0"
            family:
              ethernet_switching:
                interface_mode: trunk
                vlan:
                  members:
                    - vlan4_61
                    - vlan4_65

      # ### IRB interfaces
      - name: irb
        apply_groups:
          - IRB_OPTIONS
        unit:

          # ### VLAN 1
          - name: "1"
            family:
              inet:
                address:
                  name: "172.20.1.251/24"
                  virtual_gateway_address: "172.20.1.250"
              inet6:
                address:
                  - name: "2001:db8::172:20:1:251/112"
                    virtual_gateway_address: "2001:db8::172:20:1:250"
                  - name: "fe80::172:20:1:251/112"

          # ### VLAN 2
          - name: "2"
            family:
              inet:
                address:
                  name: "172.20.2.251/24"
                  virtual_gateway_address: "172.20.2.250"
              inet6:
                address:
                  - name: "2001:db8::172:20:2:251/112"
                    virtual_gateway_address: "2001:db8::172:20:2:250"
                  - name: "fe80::172:20:2:251/112"

          # ### VLAN 3
          - name: "3"
            family:
              inet:
                address:
                  name: "172.20.3.251/24"
                  virtual_gateway_address: "172.20.3.250"
              inet6:
                address:
                  - name: "2001:db8::172:20:3:251/112"
                    virtual_gateway_address: "2001:db8::172:20:3:250"
                  - name: "fe80::172:20:3:251/112"

      # ### LOOPBACK INTERFACES
      - name: lo0
        unit:
          - name: "0"
            description: loopback
            family:
              inet:
                address:
                  name: "{{ device.lo0.ipv4 }}/32"

          - name: "1"
            description: loopback
            family:
              inet:
                address:
                  name: "{{ device.lo1.ipv4 }}/32"
