configuration:
  protocols:

    ospf:
      area:
        - name: "0.0.0.0"
          interface:
            - name: "ae11.0"
            - name: "ae12.0"
            - name: "ae13.0"
            - name: "lo0.0"
              passive: null
