configuration:
  interfaces:
    interface:
      # ### PHYSICAL INTERFACES
      - name: xe-0/0/0
        description: "[xe-0/0/0] Connected to core1 xe-0/1/0"
        ether_options:
          ieee_802.3ad:
            bundle: ae11

      - name: xe-0/0/1
        description: "[xe-0/0/1] Connected to core1 xe-0/1/1"
        ether_options:
          ieee_802.3ad:
            bundle: ae11

      - name: xe-0/0/2
        description: "[xe-0/0/2] Connected to core1 xe-0/1/0"
        ether_options:
          ieee_802.3ad:
            bundle: ae21

      - name: xe-0/0/3
        description: "[xe-0/0/3] Connected to core1 xe-0/1/1"
        ether_options:
          ieee_802.3ad:
            bundle: ae21

      - name: ge-0/0/10
        description: "[ge-0/0/10] Connected to access-sw1 ge-2/0/0"
        ether_options:
          ieee_802.3ad:
            bundle: ae3

      - name: ge-0/0/11
        description: "[ge-0/0/11] Connected to access-sw2 ge-2/0/0"
        ether_options:
          ieee_802.3ad:
            bundle: ae4

      # ### AE INTERFACES
      - name: ae11
        description: "Connected to core-sw1 (members: xe-0/0/0 / xe-0/0/1)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "172.16.0.1/31"

      - name: ae21
        description: "Connected to core-sw2 (members: xe-0/0/2 / xe-0/0/3)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "172.17.0.1/31"

      - name: ae3
        description: "Connected to access-sw1 (members: ge-0/0/10)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
            system_id: 00:40:00:00:00:01
        esi:
          all_active: null
          identifier: 00:00:22:22:33:33:44:44:00:01
        unit:
          - name: "0"
            family:
              ethernet_switching:
                interface_mode: trunk
                vlan:
                  members:
                    - vlan_1 
                    - vlan_2 
                    - vlan_3

      - name: ae4
        description: "Connected to access-sw2 (members: ge-0/0/11)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
            system_id: 00:40:00:00:00:02
        esi:
          all_active: null
          identifier: 00:00:22:22:33:33:44:44:00:02
        unit:
          - name: "0"
            family:
              ethernet_switching:
                interface_mode: trunk
                vlan:
                  members:
                    - vlan_1 
                    - vlan_2 
                    - vlan_3

      # ### LOOPBACK INTERFACES
      - name: lo0
        unit:
          - name: "0"
            description: loopback
            family:
              inet:
                address:
                  name: "{{ device.lo0.ipv4 }}/32"
