configuration:
  protocols:

    bgp:
      group:

        # ### OVERLAY
        - name: "OVERLAY"
          type: internal
          cluster: 192.168.0.1
          local_address: "{{ device.lo0.ipv4 }}"
          family:
            evpn:
              signaling: null
          neighbor:
            - description: "dist-sw1"
              name: 192.168.1.1
            - description: "dist-sw2"
              name: 192.168.1.2
          # export: "reject-type5"
          multipath: null
          vpn_apply_export: null

    # evpn:
    #   encapsulation: "vxlan"
    #   default_gateway: "no-gateway-community"
    #   extended_vni_list:
    #     - "5001"
    #     - "5002"
    #     - "5003"

    # igmp_snooping:
    #   vlan:
    #     - name: "vlan_1"
    #       interface: "ae11.0"
    #       multicast_router_interface: null
