configuration:
  interfaces:
    interface:
      # ### PHYSICAL INTERFACES
      - name: xe-0/0/0
        description: "Connected to dist-sw1 (member of ae11)"
        ether_options:
          ieee_802.3ad:
            bundle: ae11

      - name: xe-0/0/1
        description: "Connected to dist-sw2 (member of ae12)"
        ether_options:
          ieee_802.3ad:
            bundle: ae12

      - name: xe-0/0/2
        description: "Connected to dist-sw3 (member of ae13)"
        ether_options:
          ieee_802.3ad:
            bundle: ae13

      - name: xe-0/0/3
        description: "Connected to dist-sw4 (member of ae14)"
        ether_options:
          ieee_802.3ad:
            bundle: ae14

      - name: xe-0/0/10
        description: "Connected to campus-fw2 (member of ae15)"
        ether_options:
          ieee_802.3ad:
            bundle: ae15

      - name: xe-0/0/11
        description: "Connected to campus-fw2 (member of ae16)"
        ether_options:
          ieee_802.3ad:
            bundle: ae16

      # ### AE INTERFACES
      - name: ae11
        description: "Connected to dist-sw1 (members: xe-0/0/0)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "172.16.0.2/31"

      - name: ae12
        description: "Connected to dist-sw2 (members: xe-0/0/1)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "172.16.1.2/31"

      - name: ae13
        description: "Connected to dist-sw3 (members: xe-0/0/2)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "172.16.2.2/31"

      - name: ae14
        description: "Connected to dist-sw4 (members: xe-0/0/3)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "172.16.3.2/31"

      - name: ae15
        description: "Connected to campus-rt1 (members: xe-0/0/10)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "172.16.10.3/31"

      # - name: ae16
      #   description: "Connected to campus-fw2 (members: xe-0/0/11)"
      #   apply_groups:
      #     - AE_MTU_JUMBO
      #     - AE_LACP_BOND
      #   aggregated_ether_options:
      #     lacp:
      #       active: null
      #     minimum_links: 1
      #   unit:
      #     - name: "0"
      #       family:
      #         ethernet_switching:
      #           interface_mode: trunk
      #           vlan:
      #             members:
      #               - vlan4_61
      #               - vlan4_65

      # ### LOOPBACK INTERFACES
      - name: lo0
        unit:
          - name: "0"
            description: loopback
            family:
              inet:
                address:
                  name: "{{ device.lo0.ipv4 }}/32"

      # ### MGMT INTERFACE
      - name: em0
        unit:
          name: "0"
          description: "out of band interface"
          family:
            inet:
              address:
                name: "{{ ansible_host }}/24"
                arp:
                  - name: "10.6.6.1"
                    mac: "f4:a7:39:1b:d4:9b"

      # ### vQFX PFE INTERFACE
      - name: em1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "169.254.0.2/24"

